### ISSUE TITLE
Annoying space

### ISSUE THREAD

**Issue by CptViraj** [eatcha-wikimedia/commons-rfr-archive-bot#3]
Hi, posting here as you're not active on wiki. The bot leaves annoying space when archiving requests, that's makes RFR page ugly and annoying. See [this](https://commons.wikimedia.org/w/index.php?title=Commons:Requests_for_rights&curid=6511418&diff=477758885&oldid=477758671) for example. Please fix this, Thanks!

**Comment by eatcha-wikimedia** [comment]
Fixed

**Comment by eatcha-wikimedia** [comment]
See commit https://github.com/eatcha-wikimedia/commons-rfr-archive-bot/commit/c41b2c50dbc2cbbb1d600e6d650562a1271f6ecb
