### ISSUE TITLE
Removing above space

### ISSUE THREAD

**Issue by CptViraj** [eatcha-wikimedia/commons-rfr-archive-bot#5]
Hi. On the RFR page, we have requests in the following format:
=== Request 1 ===
«Space»
=== Request 2 ===

When archiving requests, bot doesn't remove the space which is between the request and it's above request. This makes page really annoying, see https://commons.wikimedia.org/w/index.php?title=Commons:Requests_for_rights&oldid=532076391.
Can you please make bot to remove that spaces? It would be really helpful. Thanks!

**Comment by eatcha-wikimedia** [comment]
I don't understand, please edit the page as an example or provide the diff of changes requested. I can not find any trailing white-spaces (\s) left.

**Comment by CptViraj** [comment]
See https://commons.wikimedia.org/w/index.php?title=Commons:Requests_for_rights&diff=531747834&oldid=531614686, the bot removes request but not the above space.

**Comment by eatcha-wikimedia** [comment]
@CptViraj , It appears you are referring to the newline (\n) character(s). How many consecutive newlines are fine for you? 

I will set the cosmetics filter to (your )desired number of newlines between paragraphs.

**Comment by eatcha-wikimedia** [comment]
IMO, Any more than `\n\n` should probably be replaced by `\n\n `. Only one line-break between paragraphs. 

See https://gist.github.com/eatcha-wikimedia/dea1c162507cc721960842a222e8f058

**Comment by eatcha-wikimedia** [comment]
@CptViraj  Check the new edits made by the bot. If still problematic feel free to re-open this issue.
